// const [data] = useState([
  //   {
  //     name: "Thomas",
  //     Phone: "+12163547758",
  //     email: "thomas@example.com",
  //     Role: "Admin",
  //     On: "3/15/2022",
  //     Status: "Active",
  //   },
  //   {
  //     name: "504Benjamin",
  //     Phone: "123-456-888",
  //     email: "customer@example.com",
  //     Role: "Manager",
  //     On: "2/27/2022",
  //     Status: "Restricted",
  //   },
  //   {
  //     name: "James 524",
  //     Phone: "+12163547758",
  //     email: "james@example.com",
  //     Role: "Salesman",
  //     On: "2/27/2022",
  //     Status: "Restricted",
  //   },
  //   {
  //     name: "James 524",
  //     Phone: "+12163547758",
  //     email: "james@example.com",
  //     Role: "Salesman",
  //     On: "2/27/2022",
  //     Status: "Restricted",
  //   },
  //   {
  //     name: "Bruklin2022",
  //     Phone: "123-456-888",
  //     email: "bruklin@example.com",
  //     Role: "Delivery Biker",
  //     On: "2/27/2022",
  //     Status: "Active",
  //   },
  //   {
  //     name: "BeverlyWIN25",
  //     Phone: "+12163547758",
  //     email: "bruklin@example.com",
  //     Role: "Delivery Biker",
  //     On: "2/27/2022",
  //     Status: "Active",
  //   },
  //   {
  //     name: "BHR256",
  //     Phone: "123-456-888",
  //     email: "Huber@example.com",
  //     Role: "Sales Executive",
  //     On: "3/15/2022",
  //     Status: "Active",
  //   },
  //   {
  //     name: "Thomas",
  //     Phone: "+12163547758",
  //     email: "thomas@example.com",
  //     Role: "Admin",
  //     On: "3/15/2022",
  //     Status: "Active",
  //   },
  //   {
  //     name: "504Benjamin",
  //     Phone: "123-456-888",
  //     email: "customer@example.com",
  //     Role: "Manager",
  //     On: "2/27/2022",
  //     Status: "Restricted",
  //   },
  //   {
  //     name: "James 524",
  //     Phone: "+12163547758",
  //     email: "james@example.com",
  //     Role: "Salesman",
  //     On: "2/27/2022",
  //     Status: "Restricted",
  //   },
  //   {
  //     name: "James 524",
  //     Phone: "+12163547758",
  //     email: "james@example.com",
  //     Role: "Salesman",
  //     On: "2/27/2022",
  //     Status: "Restricted",
  //   },
  //   {
  //     name: "Bruklin2022",
  //     Phone: "123-456-888",
  //     email: "bruklin@example.com",
  //     Role: "Delivery Biker",
  //     On: "2/27/2022",
  //     Status: "Active",
  //   },
  //   {
  //     name: "BeverlyWIN25",
  //     Phone: "+12163547758",
  //     email: "bruklin@example.com",
  //     Role: "Delivery Biker",
  //     On: "2/27/2022",
  //     Status: "Active",
  //   },
  //   {
  //     name: "BHR256",
  //     Phone: "123-456-888",
  //     email: "Huber@example.com",
  //     Role: "Sales Executive",
  //     On: "3/15/2022",
  //     Status: "Active",
  //   },
  // ]);
  
//   const options = [
//     { id: 1, text: "Choose Product", text: "Choose Product" },
//     { id: 2, text: "Macbook pro", text: "Macbook pro" },
//     { id: 3, text: "Orange", text: "Orange" },
//   ];
//   const options2 = [
//     { id: 1, text: "Choose Category", text: "Choose Category" },
//     { id: 2, text: "Computers", text: "Computers" },
//     { id: 3, text: "Fruits", text: "Fruits" },
//   ];
//   const options3 = [
//     { id: 1, text: "Choose Sub Category", text: "Choose Sub Category" },
//     { id: 2, text: "Computers", text: "Computers" },
//   ];
//   const options4 = [
//     { id: 1, text: "Brand", text: "Brand" },
//     { id: 2, text: "N/D", text: "N/D" },
//   ];
//   const options5 = [
//     { id: 1, text: "Price", text: "Price" },
//     { id: 2, text: "150.00", text: "150.00" },
//   ];


// const [data] = useState([
//     {
//       id: 1,
//       image: Adidas,
//       brandName: "Adidas",
//       brandDescription: "shoes,sportswear",
//     },
//     {
//       id: 2,
//       image: Colgate,
//       brandName: "Colgate",
//       brandDescription: "Oral hygiene, Toothbrushes",
//     },
//     {
//       id: 3,
//       image: Samsung,
//       brandName: "Samsung",
//       brandDescription: "Electronics",
//     },
//   ]);
// const [data] = useState([
//   {
//     id: 1,
//     image: MacbookIcon,
//     categoryName: "Macbook pro",
//     categoryCode: "PT001",
//     description: "Computer Description",
//     createdBy: "Admin",
//   },
//   {
//     id: 2,
//     image: OrangeImage,
//     categoryName: "Orange",
//     categoryCode: "CTO02",
//     description: "Fruit Description",
//     createdBy: "Admin",
//   },
//   {
//     id: 3,
//     image: PineappleImage,
//     categoryName: "Pinapple",
//     categoryCode: "CTO03",
//     description: "Fruit Description",
//     createdBy: "Admin",
//   },
//   {
//     id: 4,
//     image: StawberryImage,
//     categoryName: "Strawberry",
//     categoryCode: "CTO04",
//     description: "Fruit Description",
//     createdBy: "Admin",
//   },
//   {
//     id: 5,
//     image: AvocatImage,
//     categoryName: "Avocat",
//     categoryCode: "CTO05",
//     description: "Computer Description",
//     createdBy: "Admin",
//   },
//   {
//     id: 6,
//     image: MacbookIcon,
//     categoryName: "Macbook pro",
//     categoryCode: "CTO06",
//     description: "Computer Description",
//     createdBy: "Admin",
//   },
// ]);


const [data] = useState([
  {
    id: 1,
    image: MacbookIcon,
    category: "Macbook pro",
    parentCategory: "Macbook pro",
    categoryCode: "PT001",
    description: "Computer Description",
    createdBy: "Admin",
  },
  {
    id: 2,
    image: OrangeImage,
    category: "Orange",
    parentCategory: "Orange",
    categoryCode: "CTO02",
    description: "Fruit Description",
    createdBy: "Admin",
  },
  {
    id: 3,
    image: PineappleImage,
    category: "Pinapple",
    parentCategory: "Pinapple",
    categoryCode: "CTO03",
    description: "Fruit Description",
    createdBy: "Admin",
  },
  {
    id: 4,
    image: StawberryImage,
    category: "Strawberry",
    parentCategory: "Strawberry",
    categoryCode: "CTO04",
    description: "Fruit Description",
    createdBy: "Admin",
  },
  {
    id: 5,
    image: AvocatImage,
    category: "Avocat",
    parentCategory: "Avocat",
    categoryCode: "CTO05",
    description: "Computer Description",
    createdBy: "Admin",
  },
  {
    id: 6,
    image: MacbookIcon,
    category: "Macbook pro",
    parentCategory: "Macbook pro",
    categoryCode: "CTO06",
    description: "Computer Description",
    createdBy: "Admin",
  },
]);


  // const [data] = useState([
  //   {
  //     id: 1,
  //     image: MacbookIcon,
  //     productName: "Macbook pro",
  //     sku: "PT001",
  //     category: "Computer",
  //     brand: "N/D",
  //     price: "1500.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 2,
  //     image: OrangeImage,
  //     productName: "Orange",
  //     sku: "PT002",
  //     category: "Fruits",
  //     brand: "N/D",
  //     price: "20.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 3,
  //     image: PineappleImage,
  //     productName: "Pinapple",
  //     sku: "PT003",
  //     category: "Fruits",
  //     brand: "N/D",
  //     price: "10.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 4,
  //     image: StawberryImage,
  //     productName: "Strawberry",
  //     sku: "PT004",
  //     category: "Fruits",
  //     brand: "N/D",
  //     price: "150.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 5,
  //     image: AvocatImage,
  //     productName: "Avocat",
  //     sku: "PT005",
  //     category: "Fruits",
  //     brand: "N/D",
  //     price: "1 500.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 6,
  //     image: MacbookIcon,
  //     productName: "Macbook pro",
  //     sku: "PT006",
  //     category: "Computer",
  //     brand: "N/D",
  //     price: "1500.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 7,
  //     image: EarpodIcon,
  //     productName: "Apple Earpods",
  //     sku: "PT007",
  //     category: "Computer",
  //     brand: "N/D",
  //     price: "1500.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 8,
  //     image: IphoneIcon,
  //     productName: "iPhone 11",
  //     sku: "PT008",
  //     category: "Computer",
  //     brand: "N/D",
  //     price: "1500.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 9,
  //     image: SamsungIcon,
  //     productName: "Samsung",
  //     sku: "PT009",
  //     category: "Computer",
  //     brand: "N/D",
  //     price: "120.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 10,
  //     image: EarpodIcon,
  //     productName: "Banana",
  //     sku: "PT0010",
  //     category: "Computer",
  //     brand: "N/D",
  //     price: "4500.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 11,
  //     image: MacbookIcon,
  //     productName: "Macbook pro",
  //     sku: "PT0011",
  //     category: "Computer",
  //     brand: "N/D",
  //     price: "1550.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  //   {
  //     id: 12,
  //     image: AvocatImage,
  //     productName: "Avocat",
  //     sku: "PT0012",
  //     category: "Computer",
  //     brand: "N/D",
  //     price: "1505.00",
  //     unit: "pc",
  //     qty: "100.00",
  //     createdBy: "Admin",
  //   },
  // ]);